In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import warnings
import zipfile
import warnings
import pandas as pd
warnings.filterwarnings("ignore")
# from ydata_profiling import ProfileReport
import dtale

In [2]:
# Define the path to the ZIP file
zip_path = r'C:\Users\nadav\Downloads\child-mind-institute-problematic-internet-use.zip'

In [3]:
# Open the ZIP file and read the CSV files inside
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    # Extract the names of train, test, and sample_submission files
    train_file = 'train.csv'
    test_file = 'test.csv'
    data_dictionary = 'data_dictionary.csv'

    
    # Read the CSV files into pandas DataFrames
    with zip_ref.open(train_file) as train, zip_ref.open(test_file) as test, zip_ref.open(data_dictionary) as data_dictionary:
        train = pd.read_csv(train, encoding='ISO-8859-1', delimiter=',', engine='python', on_bad_lines='skip')
        test = pd.read_csv(test, encoding='ISO-8859-1', delimiter=',', engine='python', on_bad_lines='skip')
        data_dictionary = pd.read_csv(data_dictionary, encoding='ISO-8859-1', delimiter=',', engine='python', on_bad_lines='skip')

In [4]:
train

,id,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,...,PCIAT-PCIAT_18,PCIAT-PCIAT_19,PCIAT-PCIAT_20,PCIAT-PCIAT_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday,sii
0,00008ff9,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,...,4.0,2.0,4.0,55.0,NaN,NaN,NaN,Fall,3.0,2.0
1,000fd460,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,...,0.0,0.0,0.0,0.0,Fall,46.0,64.0,Summer,0.0,0.0
2,00105258,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,...,2.0,1.0,1.0,28.0,Fall,38.0,54.0,Summer,2.0,0.0
3,00115b9f,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,...,3.0,4.0,1.0,44.0,Summer,31.0,45.0,Winter,0.0,1.0
4,0016bb22,Spring,18,1,Summer,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3955,ff8a2de4,Fall,13,0,Spring,60.0,Fall,16.362460,59.5,82.4,...,1.0,1.0,0.0,32.0,Winter,35.0,50.0,Fall,1.0,1.0
3956,ffa9794a,Winter,10,0,NaN,NaN,Spring,18.764678,53.5,76.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Winter,0.0,NaN
3957,ffcd4dbd,Fall,11,0,Spring,68.0,Winter,21.441500,60.0,109.8,...,1.0,0.0,1.0,31.0,Winter,56.0,77.0,Fall,0.0,1.0
3958,ffed1dd5,Spring,13,0,Spring,70.0,Winter,12.235895,70.7,87.0,...,1.0,1.0,1.0,19.0,Spring,33.0,47.0,Spring,1.0,0.0
3959,ffef538e,Spring,11,0,NaN,NaN,Winter,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring,1.0,NaN

In [5]:
test

,id,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,...,BIA-BIA_TBW,PAQ_A-Season,PAQ_A-PAQ_A_Total,PAQ_C-Season,PAQ_C-PAQ_C_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday
0,00008ff9,Fall,5,0,Winter,51.0,Fall,16.877316,46.00,50.8,...,32.6909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall,3.0
1,000fd460,Summer,9,0,NaN,NaN,Fall,14.035590,48.00,46.0,...,27.0552,NaN,NaN,Fall,2.340,Fall,46.0,64.0,Summer,0.0
2,00105258,Summer,10,1,Fall,71.0,Fall,16.648696,56.50,75.6,...,NaN,NaN,NaN,Summer,2.170,Fall,38.0,54.0,Summer,2.0
3,00115b9f,Winter,9,0,Fall,71.0,Summer,18.292347,56.00,81.6,...,45.9966,NaN,NaN,Winter,2.451,Summer,31.0,45.0,Winter,0.0
4,0016bb22,Spring,18,1,Summer,NaN,NaN,NaN,NaN,NaN,...,NaN,Summer,1.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,001f3379,Spring,13,1,Winter,50.0,Summer,22.279952,59.50,112.2,...,63.1265,NaN,NaN,Spring,4.110,Summer,40.0,56.0,Spring,0.0
6,0038ba98,Fall,10,0,NaN,NaN,Fall,19.660760,55.00,84.6,...,47.2211,NaN,NaN,Winter,3.670,Winter,27.0,40.0,Fall,3.0
7,0068a485,Fall,10,1,NaN,NaN,Fall,16.861286,59.25,84.2,...,50.4767,NaN,NaN,Fall,1.270,NaN,NaN,NaN,Fall,2.0
8,0069fbed,Summer,15,0,NaN,NaN,Spring,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Summer,2.0
9,0083e397,Summer,19,1,Summer,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0087dd65,Spring,11,1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring,NaN
11,00abe655,Fall,11,0,Summer,66.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Winter,1.100,Winter,42.0,59.0,Fall,0.0
12,00ae59c9,Fall,13,0,NaN,NaN,Winter,21.079065,57.75,100.0,...,56.0118,NaN,NaN,Fall,3.020,Fall,33.0,47.0,Fall,1.0
13,00af6387,Spring,12,0,NaN,NaN,Spring,15.544111,60.00,79.6,...,NaN,NaN,NaN,Spring,1.220,NaN,NaN,NaN,Spring,NaN
14,00bd4359,Spring,12,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring,2.0
15,00c0cd71,Winter,7,0,Summer,51.0,Spring,29.315775,54.00,121.6,...,NaN,NaN,NaN,NaN,NaN,Spring,35.0,50.0,Winter,2.0
16,00d56d4b,Spring,5,1,Summer,80.0,Spring,17.284504,44.00,47.6,...,NaN,NaN,NaN,NaN,NaN,Spring,37.0,53.0,Spring,0.0
17,00d9913d,Fall,10,1,NaN,NaN,Fall,19.893157,55.00,85.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall,1.0
18,00e6167c,Winter,6,0,Spring,60.0,Winter,30.094649,37.50,60.2,...,38.7638,NaN,NaN,NaN,NaN,Winter,39.0,55.0,Winter,3.0
19,00ebc35d,Winter,10,0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Winter,2.0

In [6]:
data_dictionary

,Instrument,Field,Description,Type,Values,Value Labels
0,Identifier,id,Participant's ID,str,NaN,NaN
1,Demographics,Basic_Demos-Enroll_Season,Season of enrollment,str,"Spring, Summer, Fall, Winter",NaN
2,Demographics,Basic_Demos-Age,Age of participant,float,NaN,NaN
3,Demographics,Basic_Demos-Sex,Sex of participant,categorical int,"0,1","0=Male, 1=Female"
4,Children's Global Assessment Scale,CGAS-Season,Season of participation,str,"Spring, Summer, Fall, Winter",NaN
...,...,...,...,...,...,...
76,Sleep Disturbance Scale,SDS-Season,Season of participation,str,"Spring, Summer, Fall, Winter",NaN
77,Sleep Disturbance Scale,SDS-SDS_Total_Raw,Total Raw Score,int,NaN,NaN
78,Sleep Disturbance Scale,SDS-SDS_Total_T,Total T-Score,int,NaN,NaN
79,Internet Use,PreInt_EduHx-Season,Season of participation,str,"Spring, Summer, Fall, Winter",NaN
80,Internet Use,PreInt_EduHx-computerinternet_hoursday,Hours of using computer/internet,categorical int,"0,1,2,3","0=Less than 1h/day, 1=Around 1h/day, 2=Around ..."

In [7]:
columns_in_train_not_in_test = set(train.columns) - set(test.columns)

# Print the columns
print("Columns in train but not in test:")
print(columns_in_train_not_in_test)

Columns in train but not in test:
{'PCIAT-PCIAT_20', 'PCIAT-PCIAT_02', 'PCIAT-PCIAT_09', 'PCIAT-PCIAT_11', 'PCIAT-Season', 'PCIAT-PCIAT_17', 'PCIAT-PCIAT_Total', 'PCIAT-PCIAT_04', 'PCIAT-PCIAT_16', 'PCIAT-PCIAT_19', 'PCIAT-PCIAT_10', 'PCIAT-PCIAT_05', 'PCIAT-PCIAT_03', 'PCIAT-PCIAT_18', 'PCIAT-PCIAT_07', 'PCIAT-PCIAT_15', 'PCIAT-PCIAT_08', 'PCIAT-PCIAT_14', 'PCIAT-PCIAT_06', 'PCIAT-PCIAT_12', 'sii', 'PCIAT-PCIAT_01', 'PCIAT-PCIAT_13'}

In [8]:
def calculate_stats(data, columns):
    if isinstance(columns, str):
        columns = [columns]

    stats = []
    for col in columns:
        if data[col].dtype in ['object', 'category']:
            counts = data[col].value_counts(dropna=False, sort=False)
            percents = data[col].value_counts(normalize=True, dropna=False, sort=False) * 100
            formatted = counts.astype(str) + ' (' + percents.round(2).astype(str) + '%)'
            stats_col = pd.DataFrame({'count (%)': formatted})
            stats.append(stats_col)
        else:
            stats_col = data[col].describe().to_frame().transpose()
            stats_col['missing'] = data[col].isnull().sum()
            stats_col.index.name = col
            stats.append(stats_col)

    return pd.concat(stats, axis=0)

In [9]:
df = train.isna().sum()

In [10]:
df

id                                           0
Basic_Demos-Enroll_Season                    0
Basic_Demos-Age                              0
Basic_Demos-Sex                              0
CGAS-Season                               1405
                                          ...
SDS-SDS_Total_Raw                         1351
SDS-SDS_Total_T                           1354
PreInt_EduHx-Season                        420
PreInt_EduHx-computerinternet_hoursday     659
sii                                       1224
Length: 82, dtype: int64

In [11]:
# Launch D-Tale for interactive analysis
d = dtale.show(train)
d.open_browser()  # Opens D-Tale in a browser for interactive exploration

In [ ]:
# # Generate the profiling report
# profile = ProfileReport(train, title="Loan Approval Dataset EDA Report")
# 
# # Save the report as an HTML file
# profile.to_file('ydata_profiling_report.html')
# 
# profile.to_notebook_iframe()  # Display the report inline in Jupyter

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]